project:
  type: website

website:
  title: "quartoblog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Posts
        menu:
          - href: posts/finger_exercises.ipynb
            text: Finger Exercises
          - href: posts/Floating-Point.ipynb
            text: Floating Point Arithmetics
          - href: posts/lists_mutability_cloning.ipynb
            text: Lists, Mutability and Cloning

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



